
- hosts: {{ hosts }}
  tasks:
    - name: downloading Stouts.mongodb archive
      get_url: url=https://github.com/Stouts/Stouts.mongodb/archive/{{ mongo_ver }}.tar.gz dest=/home/{{ home_dir }}/Stouts.mongodb.tar.gz
    - name: Unarchiving Stouts.mongodb Package
      unarchive: src=/home/{{ home_dir }}/Stouts.mongodb.tar.gz dest=/etc/ansible/roles
    - name: renaming roles
      command: mv /etc/ansible/roles/Stouts.mongodb-{{ mongo_ver }} /etc/ansible/roles/Stouts.mongodb
    - name: downloading ansible-role-nodejs archive
      get_url: url=https://github.com/geerlingguy/ansible-role-nodejs/archive/{{ nodejs_ver }}.tar.gz dest=/home/{{ home_dir }}/ansible-role-nodejs.tar.gz
    - name: Unarchiving ansible-role-nodejs Package
      unarchive: src=/home/{{ home_dir }}/ansible-role-nodejs.tar.gz dest=/etc/ansible/roles
    - name: renaming roles
      command: mv /etc/ansible/roles/ansible-role-nodejs-{{ nodejs_ver }} /etc/ansible/roles/ansible-role-nodejs

