node_templates:

  # This is a new ansible machine, so ansible must be installed.
  cloud_config:
    type: cloudify.nodes.CloudInit.CloudConfig
    properties:
      resource_config:
        groups:
        - wheel
        - mongodb
        - centos
        users:
          - name: { get_input: agent_user }
            primary-group: wheel
            shell: /bin/bash
            sudo: ['ALL=(ALL) NOPASSWD:ALL']
            ssh-authorized-keys:
              - { get_input: agent_key_public }
        write_files:
          - path: /etc/yum.repos.d/epel.repo
            owner: root:root
            permissions: '0444'
            content: |
              # installed by cloud-init
              [epel]
              name=Extra Packages for Enterprise Linux 7 - $basearch
              #baseurl=http://download.fedoraproject.org/pub/epel/7/$basearch
              mirrorlist=https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch
              failovermethod=priority
              enabled=1
              gpgcheck=1
              gpgkey=https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7
          - path: { get_input: ansible_log_path }
            owner: root:wheel
            permissions: '0776'
            content: ''
        packages:
          - [ansible]
          - [tar]
        runcmd:
          - sudo chown -R centos:wheel /etc/ansible

